services:
  server:
    build:
      context: .
      target: final
    ports:
      - 1000:1000
    env_file:
      - .env
    networks:
      - redis_network

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    #    volumes:
    #      - ./data/redis:/bitnami/redis/data
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge
